name: Schedule Hello World

on:
  schedule:
    - cron: '*/15 * * * *' # Run every 15 minutes

jobs:
  run-hello-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Execute hello.py script
        run: python hello.py
