name: Schedule scraper

on:
  workflow_run:
    workflows: [Schedule Hello World]
    types:
      - completed

jobs:
  run-scraper-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install bs4

      - name: Execute schedule_scraper.py script
        run: python schedule_scraper.py

